Sanctuary/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.views import static
from django.conf import settings
from django.conf.urls import url

from users.views import index

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^static/(?P<path>.*)$', static.serve,
        {'document_root': settings.STATIC_ROOT}, name='static'),
    path('', index, name='index'),  # 首页
    path('users/', include('users.urls')),  # 【用户管理】应用
    path('sjxf/', include('sjxf.urls')),  # 【数据下发】应用
    path('dataexp/', include('dataexp.urls')),  # 【数据提取】应用
    path('query/', include('dataquery.urls')),  # 【数据查询】应用
    path('infomg/', include('infomg.urls')),  # 【信息管理】应用
    path('dashboard/', include('metrics.urls')),  # 【数据看板】应用
]

sjxf/urls.py
from django.urls import path
from .views import BaseTablesView, ManualSjxf, ajax_data_relations, TaskListView, \
    DataRelationView, DataUsersView


app_name = 'sjxf'
urlpatterns = [
    path('basetables/', BaseTablesView.as_view(), name='base_table'),  # 展示已下发基础表
    path('datarelations/', DataRelationView.as_view(), name='data_relation'),  # 展示下发关系 - 农商银行与数据表 【网页初始化】
    path('manual-sjxf/', ManualSjxf.as_view(), name='manual_sjxf'),  # 手工全量数据下发
    path('get_data_relations/', ajax_data_relations, name='filter_data_relation'),  # 展示下发关系 - 农商银行与数据表 【实际数据请求-ajax】
    path('task_list/', TaskListView.as_view(), name='task_list'),  # 展示用户已创建的数据下发任务
    path('user_list/', DataUsersView.as_view(), name='user_list'),  # 展示数据下发接入用户
]

sjxf/models.py
from django.db import models
from users.models import UserInfo
# Create your models here.


class StatusTypes(models.TextChoices):
    """任务状态类型定义"""
    status_submit = '0', '已提交'
    status_execute = '1', '执行中'
    status_success = '2', '执行完成'
    status_failed = '3', '执行失败'
    status_cancel = '4', '已取消'


class BaseTables(models.Model):
    """ 数据下发基础表定义"""
    id = models.CharField(verbose_name='序号', max_length=10, primary_key=True)
    creator = models.CharField(verbose_name='模式名', max_length=50)
    table_name = models.CharField(verbose_name='下发表名', max_length=100)
    ds_id = models.CharField(verbose_name='渠道名', max_length=10)
    flag = models.BooleanField(verbose_name='是否生效')
    chn_name = models.CharField(verbose_name='表中文名', max_length=100)
    create_date = models.DateTimeField(verbose_name='创建日期')

    class Meta:
        verbose_name = '数据下发基础表'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.table_name


class DataUsers(models.Model):
    """数据下发用户"""
    user_id = models.CharField(verbose_name='用户编号', max_length=10, primary_key=True)
    org_name = models.CharField(verbose_name='机构名称', max_length=100)
    create_date = models.DateTimeField(verbose_name='接入时间')
    # address = models.GenericIPAddressField(verbose_name='IP地址')
    # port = models.IntegerField(verbose_name='端口')
    # flag = models.BooleanField(verbose_name='激活标识')
    # user_no = models.CharField(verbose_name='用户编号', max_length=10, null=True)
    # pass_no = models.CharField(verbose_name='文件密码', max_length=10, null=True)

    class Meta:
        verbose_name = '数据下发用户表'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.user_id


class DataSub(models.Model):
    id = models.BigIntegerField(verbose_name='序号', primary_key=True)
    user_id = models.CharField(verbose_name='机构编号', max_length=10, db_index=True)
    ds_id = models.CharField(verbose_name='渠道编号', max_length=10)
    ds_type = models.IntegerField(verbose_name='类型')
    t_id = models.CharField(max_length=50, verbose_name='数据表名')
    seq = models.IntegerField(verbose_name='顺序号')
    file_type = models.CharField(max_length=10, verbose_name='文件类型')
    modified = models.CharField(verbose_name='导出限定', max_length=150)
    h_sql = models.CharField(verbose_name='导出语句', max_length=2000)
    h_where = models.CharField(verbose_name='查询条件', max_length=500)
    c_user_id = models.CharField(verbose_name='村镇银行编号', max_length=10)
    a_where = models.CharField(verbose_name='全量查询条件', max_length=500)
    create_date = models.DateTimeField(verbose_name='创建日期')

    class Meta:
        verbose_name = '数据下发任务'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.user_id


class DataRelation(models.Model):
    id = models.BigIntegerField(verbose_name='序号', primary_key=True)
    user_id = models.CharField(verbose_name='机构编号', max_length=10, db_index=True)
    org_name = models.CharField(verbose_name='机构名称', max_length=100, db_index=True)
    ds_id = models.CharField(verbose_name='渠道编号', max_length=10)
    table_name = models.CharField(verbose_name='下发表名', max_length=100, db_index=True)
    # c_user_id = models.CharField(verbose_name='村镇银行编号', max_length=10)
    create_date = models.DateTimeField(verbose_name='创建日期', null=True)

    class Meta:
        verbose_name = '数据下发关系'
        verbose_name_plural = verbose_name
        ordering = ['user_id', 'ds_id']

    def __str__(self):
        return self.user_id


class TaskList(models.Model):
    task_id = models.CharField(verbose_name='任务编号', max_length=255, primary_key=True)
    user_id = models.CharField(max_length=20, verbose_name='提交人', default='admin')
    user_name = models.CharField(verbose_name='提交人姓名', max_length=50, default='')
    org_no = models.CharField(verbose_name='机构编号', max_length=10)
    table_name = models.CharField(verbose_name='下发表名', max_length=100)
    remarks = models.CharField(verbose_name='备注', max_length=100, null=True, blank=True)
    status = models.CharField(verbose_name='任务状态', choices=StatusTypes.choices, max_length=1)
    # v_flag = models.BooleanField(verbose_name='有效标识')
    created_time = models.DateTimeField(auto_now_add=True, verbose_name='创建时间')
    updated_time = models.DateTimeField(auto_now=True, verbose_name='上次修改时间')
    celery_task_id = models.CharField(verbose_name='Celery任务号', max_length=255, null=True, blank=True)

    class Meta:
        verbose_name = '下发任务清单'
        verbose_name_plural = verbose_name

    def __str__(self):
        return str(self.task_id)

sjxf/views.py
from django.shortcuts import render, HttpResponse
from django.http import JsonResponse
from django.views.generic import View
from .models import DataSub, DataUsers, BaseTables, DataRelation, TaskList, StatusTypes
from users.models import UserInfo
from sjxf.tasks import data_push
import json
import uuid
# Create your views here.


class BaseTablesView(View):
    """下发表列表"""

    def get(self, request):
        all_tables = BaseTables.objects.filter(flag=0)
        return render(request, 'sjxf/basetables.html', {'all_tables': all_tables})


class DataUsersView(View):
    """数据下发接入"""

    def get(self, request):
        all_users = DataUsers.objects.all()
        return render(request, 'sjxf/datausers.html', {'all_users': all_users})


class ManualSjxf(View):
    def get(self, request):
        users = list(DataUsers.objects.all().values('user_id', 'org_name'))
        tables = list(BaseTables.objects.filter(flag=0).values('id', 'ds_id', 'table_name'))
        context = {
            'data_users': users,
            'tables': tables,
            # 'sjxf_nav_active': True,
        }
        return render(request, 'sjxf/manualSJXF.html', context=context)

    def post(self, request):
        all_tasks = []
        username = request.user.username if request.user.username else 'admin'
        userinfo = UserInfo.objects.filter(username=username)
        if userinfo.exists():
            real_name = UserInfo.objects.get(username=username).real_name
        else:
            real_name = '手工下发'
        for organ in request.POST.getlist('org_no'):
            for table in request.POST.getlist('table_id'):
                # task_id = uuid.uuid4()
                # 取出后台全量数据下发任务所需参数值
                #     1 渠道名称：  DS_ID
                #     2 机构  号：  DUSER_ID
                #     3 数据表名：  TBNAME
                #     4 数据表ID:   T_ID
                queryset = BaseTables.objects.get(id=table)
                ds_id = queryset.ds_id
                tb_name = queryset.table_name
                # t_id = queryset.id
                # 检验数据表与下发机构是否匹配
                result = DataSub.objects.filter(user_id=organ, t_id=table)
                remarks = ''
                task_id = uuid.uuid4()
                if not result.exists():
                    remarks = f'该行未配置下发表{tb_name}'
                    status = StatusTypes.status_cancel
                    celery_task_id = ''
                else:
                    # 调用celery异步任务
                    push = data_push.delay(ds_id, organ, tb_name, table, task_id)
                    status = StatusTypes.status_submit
                    celery_task_id = push.task_id
                task = TaskList(task_id=task_id, user_id=username, user_name=real_name,
                                org_no=organ, table_name=tb_name, status=status,
                                remarks=remarks, celery_task_id=celery_task_id)
                task.save()
                all_tasks.append(TaskList.objects.get(task_id=task_id))
        return render(request, 'sjxf/tasklist.html', {'all_tasks': all_tasks})


class DataRelationView(View):
    def get(self, request):
        return render(request, 'sjxf/datarelations.html')


def ajax_data_relations(request):
    relation_list = []
    if request.method == 'POST':
        org_no = request.POST.get('org_no')
        table_name = request.POST.get('table_name')
        if org_no:
            relations = DataRelation.objects.filter(user_id=org_no)  # 按机构号精准匹配
        elif table_name:
            if len(table_name.strip()) >= 4:
                relations = DataRelation.objects.filter(table_name__icontains=table_name)  # 按表名模糊匹配
            else:
                relations = []
        else:
            relations = DataRelation.objects.all()[:200]  # 默认返回数据表前200条记录进行展示
        for relation_info in relations:
            relation_list.append({
                'user_id': relation_info.user_id,
                'org_name': relation_info.org_name,
                'ds_id': relation_info.ds_id,
                'table_name': relation_info.table_name,
                # 'c_user_id': relation_info.c_user_id,
                # 前端ajax请求datetime格式数据需要转换
                'create_date':
                    relation_info.create_date.strftime('%Y-%m-%d %H:%M:%S')
                    if relation_info.create_date
                    else '',
            })
        return HttpResponse(json.dumps(relation_list), content_type="application/json")


class TaskListView(View):
    def get(self, request):
        username = request.user.username
        all_tasks = TaskList.objects.filter(user_id=username)
        return render(request, 'sjxf/tasklist.html', {'all_tasks': all_tasks})

templates/sjxf/basetables.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
数据下发基础表
{% endblock %}

{% block custom_css %}
<link href="{% static 'css/plugins/dataTables/datatables.min.css' %}" rel="stylesheet">
{% endblock %}

{#{% block content-header %}#}
{#<div class="row wrapper border-bottom white-bg page-heading">#}
{#    <div class="col-lg-12">#}
{#        <h2>数据下发</h2>#}
{#        <ol class="breadcrumb">#}
{#            <li class="breadcrumb-item">#}
{#                <a href="#">首页</a>#}
{#            </li>#}
{#            <li class="breadcrumb-item active">#}
{#                <strong>已下发基础表</strong>#}
{#            </li>#}
{#        </ol>#}
{#    </div>#}
{#    <div class="col-lg-2">#}
{#    </div>#}
{#</div>#}
{#{% endblock %}#}

{% block content %}
<div class="wrapper wrapper-content animated fadeInRight">
    <div class="row">
        <div class="col-lg-12">
            <div class="ibox ">
                <div class="ibox-title">
                    <h5>已下发基础表</h5>
                </div>
                <div class="ibox-content">
                    <div class="table-responsive">
                        <table class="table table-striped table-bordered table-hover dataTables-example" >
                            <thead>
                            <tr>
                                <th>序号</th>
                                <th>模式名</th>
                                <th>表名</th>
                                <th>渠道名</th>
                                <th>表中文名</th>
                                <th>创建时间</th>
                            </tr>
                            </thead>
                            <tbody>
                            {% for table in all_tables %}
                                <tr>
                                    <td>{{ forloop.counter }}</td>
                                    <td>{{ table.creator }}</td>
                                    <td>{{ table.table_name }}</td>
                                    <td>{{ table.ds_id }}</td>
                                    <td>{{ table.chn_name }}</td>
                                    <td>{{ table.create_date }}</td>
                                </tr>
                            {% endfor %}
                            </tbody>
                            <tfoot>
                            <tr>
                                <th>序号</th>
                                <th>模式名</th>
                                <th>表名</th>
                                <th>渠道名</th>
                                <th>表中文名</th>
                                <th>创建时间</th>
                            </tr>
                            </tfoot>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

{% block custom_js %}
    <script src="{% static 'js/plugins/metisMenu/jquery.metisMenu.js' %}"></script>
    <script src="{% static 'js/plugins/slimscroll/jquery.slimscroll.min.js' %}"></script>
    <script src="{% static 'js/plugins/dataTables/datatables.min.js' %}"></script>
{#    <script src="{% static 'js/plugins/dataTables/dataTables.bootstrap4.min.js' %}"></script>#}

    <script src="{% static 'js/inspinia.js' %}"></script>
    <script src="{% static 'js/plugins/pace/pace.min.js' %}"></script>
{% endblock %}

{% block custom_page_js %}
    <script>
        $.fn.dataTable.Buttons.defaults.dom.button.className = 'btn btn-white btn-sm';

        $(document).ready(function(){
            $('.dataTables-example').DataTable({
                pageLength: 25,
                responsive: true,
                dom: '<"html5buttons"B>lTfgitp',
                language: {
                    lengthMenu: "选择每页 _MENU_ 展示 ",
                    zeroRecords: "未找到匹配结果",
                    info: "当前显示第 _PAGE_ 页结果，共 _PAGES_ 页",
                    infoEmpty: "没有数据",
                    infoFiltered: "(获取 _MAX_ 项结果)",
                    paginate: {
                        first: "首页",
                        previous: "上一页",
                        next: "下一页",
                        last: "末页"
                    },
                },
                buttons: [
                    {extend: 'copy'},
                    {extend: 'csv'},
                    {extend: 'excel', title: 'ExampleFile'},
                    {extend: 'pdf', title: 'ExampleFile'},
                    {
                        extend: 'print', customize: function (win) {
                            $(win.document.body).addClass('white-bg');
                            $(win.document.body).css('font-size', '10px');
                            $(win.document.body).find('table').addClass('compact').css('font-size', 'inherit');
                        }
                    }
                ]
            });
        });
    </script>
{% endblock %}

templates/sjxf/datarelations.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
数据下发基础表
{% endblock %}

{% block custom_css %}
<link href="{% static 'css/plugins/dataTables/datatables.min.css' %}" rel="stylesheet">
{% endblock %}

{#{% block content-header %}#}
{#<div class="row wrapper border-bottom white-bg page-heading">#}
{#    <div class="col-lg-12">#}
{#        <h2>数据下发</h2>#}
{#        <ol class="breadcrumb">#}
{#            <li class="breadcrumb-item">#}
{#                <a href="#">首页</a>#}
{#            </li>#}
{#            <li class="breadcrumb-item active">#}
{#                <strong>已下发基础表</strong>#}
{#            </li>#}
{#        </ol>#}
{#    </div>#}
{#    <div class="col-lg-2">#}
{#    </div>#}
{#</div>#}
{#{% endblock %}#}

{% block content %}
<div class="wrapper wrapper-content animated fadeInRight">
    <div class="row">
        <div class="col-lg-12">
            <div class="ibox">
                <div class="ibox-title">
                    <h5>下发数据关系表</h5>
                </div>
                <div class="ibox-content">
                    <div class="row col-sm-12">
                        <input type="text" class="form-control input-sm m-b-xs col-sm-2" style="margin-left: 15px"
                               name="filter_organ_no" placeholder="按机构号搜索" value="" autocomplete="off">
                        <input type="text" class="form-control input-sm m-b-xs col-sm-2"
                               name="filter_table_name" placeholder="按表名搜索" value="" autocomplete="off"
                        style="margin-left: 40px">
                    </div>
                    <div class="hr-line-dashed"></div>
                    <div class="table-responsive">
                        <table class="table table-striped table-bordered table-hover dataTables-example" >
                            <thead>
                            <tr>
                                <th>序号</th>
                                <th>机构号</th>
                                <th>机构名称</th>
                                <th>渠道号</th>
                                <th>表名</th>
{#                                <th>村镇银行机构号</th>#}
                                <th>创建日期</th>
                            </tr>
                            </thead>
                            <tbody>
{#                            {% for relation in relations %}#}
{#                                <tr>#}
{#                                    <td>{{ relation.user_id }}</td>#}
{#                                    <td>{{ relation.org_name }}</td>#}
{#                                    <td>{{ relation.ds_id }}</td>#}
{#                                    <td>{{ relation.table_name }}</td>#}
{#                                    <td>{{ relation.c_user_id }}</td>#}
{#                                    <td>{{ relation.create_date }}</td>#}
{#                                </tr>#}
{#                            {% endfor %}#}
                            </tbody>
                            <tfoot>
                            <tr>
                                <th>序号</th>
                                <th>机构号</th>
                                <th>机构名称</th>
                                <th>渠道号</th>
                                <th>表名</th>
{#                                <th>村镇银行机构号</th>#}
                                <th>创建日期</th>
                            </tr>
                            </tfoot>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

{% block custom_js %}
    <script src="{% static 'js/plugins/metisMenu/jquery.metisMenu.js' %}"></script>
    <script src="{% static 'js/plugins/slimscroll/jquery.slimscroll.min.js' %}"></script>
    <script src="{% static 'js/plugins/dataTables/datatables.min.js' %}"></script>

    <script src="{% static 'js/inspinia.js' %}"></script>
    <script src="{% static 'js/plugins/pace/pace.min.js' %}"></script>
{% endblock %}

{% block custom_page_js %}
    <script>

        $.fn.dataTable.Buttons.defaults.dom.button.className = 'btn btn-white btn-sm';
        function createDataTable(org_no='', table_name='') {
            $('.dataTables-example').DataTable({
                pageLength: 25,
                responsive: true,
                dom: '<"html5buttons"B>lTfgitp',
                destroy: true,
                {#autoWidth: true,#}
                language: {
                    lengthMenu: "选择每页 _MENU_ 展示 ",
                    zeroRecords: "未找到匹配结果",
                    info: "当前显示第 _PAGE_ 页结果，共 _PAGES_ 页",
                    infoEmpty: "没有数据",
                    infoFiltered: "(获取 _MAX_ 项结果)",
                    paginate: {
                        first: "首页",
                        previous: "上一页",
                        next: "下一页",
                        last: "末页"
                }
            },
                columns: [
                    {
                        data: null,
                        'render': function (data, type, full, meta) {
                            return meta.row + 1 + meta.settings._iDisplayStart;
                        }
                    },
                    { data: 'user_id' },
                    { data: 'org_name' },
                    { data: 'ds_id' },
                    { data: 'table_name' },
                    {#{ data: 'c_user_id' },#}
                    { data: 'create_date' },
                ],
                buttons: [
                    {
                        extend: 'copy'
                    },
                    {
                        extend: 'csv'
                    },
                    {
                        extend: 'excel', title: 'ExampleFile'
                    },
                    {
                        extend: 'pdf', title: 'ExampleFile'
                    },

                    {
                        extend: 'print',
                        customize: function (win) {
                            $(win.document.body).addClass('white-bg');
                            $(win.document.body).css('font-size', '10px');
                            $(win.document.body).find('table').addClass('compact').css('font-size', 'inherit');
                        }
                    },
                ],
                ajax: {
                    url: '{% url 'sjxf:filter_data_relation' %}',
                    data: {
                        'org_no': org_no,
                        'table_name': table_name,
                        csrfmiddlewaretoken: '{{ csrf_token }}',
                    },
                    type: 'post',
                    dataSrc: '',
                }
            });
        }
        $(document).ready(function(){
            let org_no = $("input[name='filter_organ_no']").val();
            let table_name = $("input[name='filter_table_name']").val();
            createDataTable(org_no, table_name)
            $(':input').bind("input propertychange", function(event) {
                org_no = $("input[name='filter_organ_no']").val();
                table_name = $("input[name='filter_table_name']").val();
                if ($(this).attr('name') === 'filter_organ_no') table_name = ''
                else org_no = '';
                createDataTable(org_no, table_name)
            });
        });

    </script>
{% endblock %}

templates/sjxf/manualSJXF.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
手工下发数据
{% endblock %}

{% block custom_css %}
    <link href="{% static 'css/plugins/iCheck/custom.css' %}" rel="stylesheet">
    <link href="{% static 'css/plugins/bootstrap-tagsinput/bootstrap-tagsinput.css' %}" rel="stylesheet">
    <link href="{% static 'css/plugins/colorpicker/bootstrap-colorpicker.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/plugins/cropper/cropper.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/plugins/switchery/switchery.css' %}" rel="stylesheet">
    <link href="{% static 'css/plugins/jasny/jasny-bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/plugins/nouslider/jquery.nouislider.css' %}" rel="stylesheet">
    <link href="{% static 'css/plugins/datapicker/datepicker3.css' %}" rel="stylesheet">
    <link href="{% static 'css/plugins/ionRangeSlider/ion.rangeSlider.css' %}" rel="stylesheet">
    <link href="{% static 'css/plugins/awesome-bootstrap-checkbox/awesome-bootstrap-checkbox.css' %}" rel="stylesheet">
    <link href="{% static 'css/plugins/clockpicker/clockpicker.css' %}" rel="stylesheet">
    <link href="{% static 'css/plugins/daterangepicker/daterangepicker-bs3.css' %}" rel="stylesheet">
    <link href="{% static 'css/plugins/select2/select2.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/plugins/select2/select2-bootstrap4.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/plugins/touchspin/jquery.bootstrap-touchspin.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/plugins/dualListbox/bootstrap-duallistbox.min.css' %}" rel="stylesheet">
{% endblock %}

{% block content %}
    <div class="wrapper wrapper-content animated fadeIn">
        <div class="row">
            <div class="col-lg-12">
                <div class="ibox">
                    <div class="ibox-title">
                        <h5>选择要下发的机构和数据表</h5>
                    </div>
                    <div class="ibox-content">
                        <form action="{% url 'sjxf:manual_sjxf' %}" class="wizard-big" method="post"
                              enctype="multipart/form-data">
                            {% csrf_token %}
                            <div class="row col-sm-12">
                                <div class="col-sm-6">
                                    <select class="form-control dual_select" multiple name="org_no">
                                        {% for data_user in data_users %}
                                            <option value="{{ data_user.user_id }}">
                                                {{ data_user.user_id }} | {{ data_user.org_name }}
                                            </option>
                                        {% endfor %}
                                    </select>
                                </div>
                                <div class="col-sm-6">
                                    <select class="form-control dual_select" multiple name="table_id">
                                        {% for table in tables %}
                                            <option value="{{ table.id }}">
                                                {{ table.ds_id }}.{{ table.table_name }}
                                            </option>
                                        {% endfor %}
                                    </select>
                                </div>
                            </div>
                            <div class="hr-line-dashed"></div>
                            <div class="row form-group col-sm-12">
                                <div class="col-sm-4 col-sm-offset-2">
                                    <button class="btn btn-white btn-lg" type="submit" style="margin-right: 40px"
                                            name="cancel">
                                        取消
                                    </button>
                                    <button class="btn btn-primary btn-lg" type="submit" id="submit" name="submit">
                                        提交
                                    </button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

{% block custom_js %}
    <script src="{% static 'js/inspinia.js' %}"></script>
    <script src="{% static 'js/plugins/pace/pace.min.js' %}"></script>
    <script src="{% static 'js/plugins/slimscroll/jquery.slimscroll.min.js' %}"></script>
    <!-- JSKnob -->
    <script src="{% static 'js/plugins/jsKnob/jquery.knob.js' %}"></script>
    <!-- Input Mask-->
    <script src="{% static 'js/plugins/jasny/jasny-bootstrap.min.js' %}"></script>
    <!-- Data picker -->
    <script src="{% static 'js/plugins/datapicker/bootstrap-datepicker.js' %}"></script>
    <!-- NouSlider -->
    <script src="{% static 'js/plugins/nouslider/jquery.nouislider.min.js' %}"></script>
    <!-- Switchery -->
    <script src="{% static 'js/plugins/switchery/switchery.js' %}"></script>
    <!-- IonRangeSlider -->
    <script src="{% static 'js/plugins/ionRangeSlider/ion.rangeSlider.min.js' %}"></script>
    <!-- iCheck -->
    <script src="{% static 'js/plugins/iCheck/icheck.min.js' %}"></script>
    <!-- MENU -->
    <script src="{% static 'js/plugins/metisMenu/jquery.metisMenu.js' %}"></script>
    <!-- Color picker -->
    <script src="{% static 'js/plugins/colorpicker/bootstrap-colorpicker.min.js' %}"></script>
    <!-- Clock picker -->
    <script src="{% static 'js/plugins/clockpicker/clockpicker.js' %}"></script>
    <!-- Image cropper -->
    <script src="{% static 'js/plugins/cropper/cropper.min.js' %}"></script>
    <!-- Date range use moment.js same as full calendar plugin -->
    <script src="{% static 'js/plugins/fullcalendar/moment.min.js' %}"></script>
    <!-- Date range picker -->
    <script src="{% static 'js/plugins/daterangepicker/daterangepicker.js' %}"></script>
    <!-- Select2 -->
    <script src="{% static 'js/plugins/select2/select2.full.min.js' %}"></script>
    <!-- TouchSpin -->
    <script src="{% static 'js/plugins/touchspin/jquery.bootstrap-touchspin.min.js' %}"></script>
    <!-- Tags Input -->
    <script src="{% static 'js/plugins/bootstrap-tagsinput/bootstrap-tagsinput.js' %}"></script>
    <!-- Dual Listbox -->
    <script src="{% static 'js/plugins/dualListbox/jquery.bootstrap-duallistbox.js' %}"></script>

{% endblock %}

{% block custom_page_js %}

    <script>
        $(document).ready(function () {
            $('.i-checks').iCheck({
                checkboxClass: 'icheckbox_square-green',
                radioClass: 'iradio_square-green',
            });

            $('.tagsinput').tagsinput({
                tagClass: 'label label-primary'
            });

            $('.dual_select').bootstrapDualListbox({
                selectorMinimalHeight: 300,
                moveOnDoubleClick: true,
                moveOnSelect: false,
            });
            <!-- 提交按钮默认不可提交 -->
            $("button[name='submit']").attr("disabled", true);
        });
        <!-- 点击取消按钮清空select选中的值 -->
        $("button[name='cancel']").click(function () {
            $("select[name='org_no_helper2']").empty();
            $("select[name='org_no']").find('option:selected').remove()
            $("select[name='table_id_helper2']").empty();
            $("select[name='table_id']").find('option:selected').remove()
            return false;
        });
        <!-- 机构和数据表同时选中值才可以点击 -->
        $("select[name='org_no'], select[name='table_id']").change(function() {
            const org_no_select = $("select[name='org_no']").val()
            const table_id_select = $("select[name='table_id']").val()
            if (org_no_select.length !== 0 && table_id_select.length !== 0)
                $("button[name='submit']").attr("disabled", false);
            else $("button[name='submit']").attr("disabled", true);
        })

    </script>

{% endblock %}