Sanctuary/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.views import static
from django.conf import settings
from django.conf.urls import url

from users.views import index

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^static/(?P<path>.*)$', static.serve,
        {'document_root': settings.STATIC_ROOT}, name='static'),
    path('', index, name='index'),  # 首页
    path('users/', include('users.urls')),  # 【用户管理】应用
    path('sjxf/', include('sjxf.urls')),  # 【数据下发】应用
    path('dataexp/', include('dataexp.urls')),  # 【数据提取】应用
    path('query/', include('dataquery.urls')),  # 【数据查询】应用
    path('infomg/', include('infomg.urls')),  # 【信息管理】应用
    path('dashboard/', include('metrics.urls')),  # 【数据看板】应用
]

infomg/urls.py
from django.urls import path
from infomg.views import *


app_name = 'InfoMG'
urlpatterns = [
    path('defect_import/', defect_import, name='defect_imp'),  # 基础软硬件缺陷导入
    path('defect_list/', defect_list, name='defect_list'),  # 基础软硬件缺陷查看
    path('defect_detail/', defect_detail, name='defect_detail'),  # 缺陷明细查看
    path('add_defect_detail/', add_defect_detail, name='default_add_defect_detail'),  # 增加产品/软件待处理记录
    path('add_defect_detail/<int:defect_id>/', add_defect_detail, name='add_defect_detail'),  # 增加产品/软件待处理记录 - 页面跳转
    path('ajax_get_defect/', ajax_get_defect, name='ajax_get_defect'),  # 根据缺陷期数筛选具体缺陷列表
    path('save_defect_detail/', save_defect_detail, name='save_defect_detail'),  # 保存待处理缺陷记录
    path('delete_defect_detail/', ajax_dlt_defect_detail, name='dlt_defect_detail'),  # 删除待处理缺陷记录
    path('add_detail_solved_date/', ajax_update_solved_date, name='add_solved_date'),  # 修改待处理缺陷记录的实际解决日期
    path('update_defect_v_solution/', ajax_update_v_solution, name='add_v_solution'),  # 添加产品缺陷记录的行内解决方案
    path('update_defect_v_flag/', ajax_update_defect_v_flag, name='update_defect_v_flag'),  # 更新产品缺陷记录的行内解决状态
]

sjxf/urls.py
from django.urls import path
from .views import BaseTablesView, ManualSjxf, ajax_data_relations, TaskListView, \
    DataRelationView, DataUsersView


app_name = 'sjxf'
urlpatterns = [
    path('basetables/', BaseTablesView.as_view(), name='base_table'),  # 展示已下发基础表
    path('datarelations/', DataRelationView.as_view(), name='data_relation'),  # 展示下发关系 - 农商银行与数据表 【网页初始化】
    path('manual-sjxf/', ManualSjxf.as_view(), name='manual_sjxf'),  # 手工全量数据下发
    path('get_data_relations/', ajax_data_relations, name='filter_data_relation'),  # 展示下发关系 - 农商银行与数据表 【实际数据请求-ajax】
    path('task_list/', TaskListView.as_view(), name='task_list'),  # 展示用户已创建的数据下发任务
    path('user_list/', DataUsersView.as_view(), name='user_list'),  # 展示数据下发接入用户
]

infomg/models.py
from django.db import models


# Create your models here.


class ProductDefect(models.Model):
    """基础软件缺陷总表"""
    periods = models.CharField(max_length=7, verbose_name='期数')
    # number = models.IntegerField(verbose_name='序号')
    category = models.CharField(verbose_name='产品类型', max_length=50)
    model = models.CharField(verbose_name='设备型号/软件版本', max_length=200)
    manufacturer = models.CharField(max_length=100, verbose_name='生产厂商')
    reason = models.TextField(verbose_name='缺陷原因')
    defect = models.CharField(max_length=20, verbose_name='缺陷影响')
    solution = models.TextField(verbose_name='解决方案')
    fix_pack = models.CharField(max_length=200, verbose_name='补丁版本')
    status = models.CharField(max_length=10, verbose_name='解决状态')
    find_date = models.DateField(verbose_name='发现时间')
    v_solution = models.CharField(max_length=200, verbose_name='行内解决方案', null=True)
    # v_flag = models.BooleanField(verbose_name='行内解决状态', default=False)
    v_flag = models.CharField(verbose_name='行内解决状态',
                              choices=((0, '待解决'), (1, '已解决'), (2, '无需处理')), max_length=1)

    def __str__(self):
        return self.model

    class Meta:
        verbose_name = '基础软硬件产品缺陷信息表'
        verbose_name_plural = verbose_name
        unique_together = (
            'periods', 'category', 'model', 'manufacturer', 'defect',
            'fix_pack', 'status', 'find_date',
        )


class DefectDetail(models.Model):
    """缺陷明细记录表"""
    periods = models.CharField(max_length=7, verbose_name='期数')
    model = models.ForeignKey(ProductDefect, on_delete=models.CASCADE, verbose_name='设备型号/软件版本')
    system = models.CharField(verbose_name='涉及系统', max_length=10)
    solution = models.TextField(verbose_name='解决方案', null=True)
    status = models.BooleanField(verbose_name='解决状态', default=False)
    solve_date = models.DateField(verbose_name='拟解决日期', null=True)
    solved_date = models.DateField(verbose_name='解决日期', null=True)

    def __str__(self):
        return self.system

    class Meta:
        verbose_name = '缺陷明细记录表'
        verbose_name_plural = verbose_name
        unique_together = (
            'periods', 'model', 'system',
        )

infomg/views.py
from django.shortcuts import render, HttpResponse, HttpResponseRedirect
from infomg.models import ProductDefect, DefectDetail
from django.db import transaction
import xlrd
from xlrd import xldate_as_tuple
from datetime import datetime
import json
from django.http import JsonResponse
from django.urls import reverse


# Create your views here.


def defect_import(request):
    """导入软硬件缺陷列表"""
    if request.method == 'GET':
        return render(request, 'infomg/defect_imp.html')
    elif request.method == 'POST':
        f = request.FILES.get('file')
        periods = request.POST.get('periods')
        excel_type = f.name.split('.')[-1]
        if excel_type in ['xls', 'xlsx']:
            wb = xlrd.open_workbook(filename=None, file_contents=f.read())
            table = wb.sheets()[0]
            rows = table.nrows
            try:
                with transaction.atomic():
                    for i in range(3, rows):
                        i_row = table.row_values(i)
                        try:
                            number = int(i_row[0])
                        except Exception as e:
                            break
                        category = i_row[1]
                        if category not in ['数据库', '中间件', '其它']:  # 只关注数据库、中间件和其它这三个产品类型
                            continue
                        try:
                            model = i_row[2].replace('\n', ' ')
                        except Exception as e:
                            model = i_row[2]
                        manufacturer = i_row[3]
                        reason = i_row[4].replace('\n', ' ')
                        defect = i_row[5]
                        solution = i_row[6].replace('\n', ' ')
                        try:
                            fix_pack = i_row[7].replace('\n', ' ')
                        except Exception as e:
                            fix_pack = i_row[7]
                        status = i_row[8]
                        find_date = datetime(*xldate_as_tuple(i_row[9], 0))
                        task = ProductDefect(periods=periods, category=category, model=model,
                                             manufacturer=manufacturer, reason=reason,
                                             defect=defect, solution=solution, fix_pack=fix_pack,
                                             status=status, find_date=find_date)
                        task.save()
                all_defects = ProductDefect.objects.filter(periods=periods).values()
                return HttpResponseRedirect(reverse('InfoMG:defect_list'),
                                            {'all_defects': all_defects, 'periods': periods})
            except Exception as e:
                print(e)


def defect_list(request):
    """展示软硬件缺陷列表"""
    if request.method == 'GET':
        all_defects = ProductDefect.objects.all().values()
        all_details_count = 0  # 计算一条缺陷下创建待处理明细条数
        solved_details_count = 0  # 待处理明细已处理数量
        for defect in all_defects:
            try:
                details = DefectDetail.objects.filter(model=defect['id'])
                all_details_count = details.count()  # 计算一条缺陷下创建待处理明细条数
                for detail in details:
                    if detail.status:
                        solved_details_count += 1
            except Exception as e:
                pass
            defect['all_details_count'] = all_details_count
            defect['solved_details_count'] = solved_details_count
        return render(request, 'infomg/defect_list.html', {'all_defects': all_defects})


def defect_detail(request):
    details = DefectDetail.objects.all()
    return render(request, 'infomg/defect_detail.html', {'details': details})


def add_defect_detail(request, defect_id=None):
    if request.method == 'GET':
        if defect_id:
            defects = ProductDefect.objects.get(pk=defect_id)
            return render(request, 'infomg/add_defect_detail.html', {'defects': defects})
        else:
            defects = ProductDefect.objects.all()
            periods = ProductDefect.objects.all().values('periods').distinct()
            return render(request, 'infomg/add_defect_detail.html', {'defects': defects, 'periods': periods})


def ajax_get_defect(request):
    periods = request.POST.get('periods')
    defect_models = list(ProductDefect.objects.filter(periods=periods).values('model'))
    return HttpResponse(json.dumps(defect_models), content_type="application/json")


def save_defect_detail(request):
    if request.method == 'POST':
        systems = request.POST.getlist('system')
        solutions = request.POST.getlist('solution')
        solve_dates = request.POST.getlist('solve_date')
        periods = request.POST.get('periods')
        defect_model = request.POST.get('defect_model')
        defect_model_id = ProductDefect.objects.get(model=defect_model, periods=periods)
        counts = len(systems)
        for i in range(0, counts):
            DefectDetail.objects.create(periods=periods, model=defect_model_id, system=systems[i],
                                        solution=solutions[i], solve_date=solve_dates[i])
        details = DefectDetail.objects.filter(periods=periods)
        # return render(request, 'infomg/defect_detail.html', {'details': details})
        return HttpResponseRedirect(reverse('InfoMG:defect_detail'), {'details': details})


def ajax_dlt_defect_detail(request):
    if request.method == 'POST':
        defect_id = request.POST.get('defect_id')
        try:
            # periods = DefectDetail.objects.get(pk=defect_id).periods
            DefectDetail.objects.get(pk=defect_id).delete()
            # detail_obj = DefectDetail.objects.filter(periods=periods)
            return HttpResponse('success')
        except Exception as e:
            return HttpResponse('failed')


def ajax_update_solved_date(request):
    if request.method == 'POST':
        detail_id = request.POST.get('detail_id')
        solved_date = request.POST.get('solved_date')
        DefectDetail.objects.filter(pk=detail_id).update(solved_date=solved_date, status=True)
        # 如果一条缺陷对应的待处理明细都已经解决，则该缺陷应被修改为已完成。
        defect_id = DefectDetail.objects.get(pk=detail_id).model_id
        periods = DefectDetail.objects.get(pk=detail_id).periods
        if not DefectDetail.objects.filter(model=defect_id, periods=periods, status=False):
            ProductDefect.objects.filter(pk=defect_id).update(v_flag=True)
        return HttpResponse('success')


def ajax_update_v_solution(request):
    """更新产品缺陷的整体解决方案"""
    if request.method == 'POST':
        defect_id = request.POST.get('defect_id')
        v_solution = request.POST.get('v_solution')
        try:
            ProductDefect.objects.filter(pk=defect_id).update(v_solution=v_solution, v_flag=0)
            return HttpResponse('success')
        except Exception as e:
            return HttpResponse('failed')


def ajax_update_defect_v_flag(request):
    """更新产品缺陷的行内处理状态"""
    if request.method == 'POST':
        defect_id = request.POST.get('defect_id')
        v_solution = request.POST.get('v_solution')
        try:
            ProductDefect.objects.filter(pk=defect_id).update(v_flag=2, v_solution=v_solution)
            return HttpResponse('success')
        except Exception as e:
            return HttpResponse('failed')

templates/infomg/defect_imp.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
基础软硬件缺陷导入
{% endblock %}

{% block custom_css %}
    <link href="{% static 'css/plugins/datapicker/datepicker3.css' %}" rel="stylesheet">
{% endblock %}

<!-- 主页内容头部 -->
{% block content-header %}
    <div class="row wrapper border-bottom white-bg page-heading">
        <div class="col-lg-10">
            <h2>数据提取信息登记</h2>
            <ol class="breadcrumb">
                <li class="breadcrumb-item">
                    <a href="#">首页</a>
                </li>
                <li class="breadcrumb-item active">
                    <strong>信息登记</strong>
                </li>
            </ol>
        </div>
        <div class="col-lg-2">
        </div>
    </div>
{% endblock %}
<!-- 主页正文 -->
{% block content %}
    <div class="wrapper wrapper-content animated fadeIn">
        <div class="row">
            <div class="col-lg-12">
                <div class="ibox">
                    <div class="ibox-content">
                        <h3></h3>
                        <p></p>
                        <form class="m-t-md" enctype="multipart/form-data"
                              action="{% url 'InfoMG:defect_imp' %}" method="post">
                            {% csrf_token %}
                            <div class="col-sm-5 row toggle-show" >
                                    <label class="font-norma">录入期数</label>
                                    <div class="input-group date">
                                        <span class="input-group-addon">
                                            <i class="fa fa-calendar"></i>
                                        </span>
                                        <input type="text" class="form-control" value=""
                                               name="periods" required>
                                    </div>
                                </div>
                            <div class="hr-line-dashed"></div>
                            <div class="form-group row col-sm-12">
                                <div class="custom-file col-sm-5">
                                    <input id="logo" type="file" class="custom-file-input" name="file" required>
                                    <label for="logo" class="custom-file-label">选择文件...</label>
                                </div>
                                <div class="col-sm-1"></div>
                            </div>
                            <div class="hr-line-dashed"></div>
                            <div class="form-group row">
                                <div class="col-sm-12">
                                    <button class="btn btn-primary btn-lg col-sm-2 offset-sm-1" type="submit">提交</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block custom_js %}
    <script src="{% static 'js/inspinia.js' %}"></script>
    <script src="{% static 'js/plugins/pace/pace.min.js' %}"></script>
    <script src="{% static 'js/plugins/metisMenu/jquery.metisMenu.js' %}"></script>
    <script src="{% static 'js/plugins/slimscroll/jquery.slimscroll.min.js' %}"></script>
    <!-- Data picker -->
    <script src="{% static 'js/plugins/datapicker/bootstrap-datepicker.js' %}"></script>

{% endblock %}

{% block custom_page_js %}

    <script>

        $(document).ready(function(){
            $('.input-group.date').datepicker({
                minViewMode: 1,
                keyboardNavigation: false,
                forceParse: false,
                autoclose: true,
                todayHighlight: true,
                format: "yyyy-mm",
            });
        });
        <!-- 上传文件 -->
        $('.custom-file-input').on('change', function() {
            let fileName = $(this).val().split('\\').pop();
            $(this).next('.custom-file-label').addClass("selected").html(fileName);
        });
    </script>

{% endblock %}

templates/infomg/defect_list.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
基础软硬件缺陷清单
{% endblock %}

{% block custom_css %}
<link href="{% static 'css/plugins/footable/footable.core.css' %}" rel="stylesheet">
{% endblock %}

{% block content-header %}
    <div class="row wrapper border-bottom white-bg page-heading">
        <div class="col-lg-10">
            <h2>软硬件缺陷清单</h2>
            <ol class="breadcrumb">
                <li class="breadcrumb-item">
                    <a href="#">首页</a>
                </li>
                <li class="breadcrumb-item active">
                    缺陷清单 -
                    <strong>
                        {% if periods %}
                            {{ periods|slice:":4"}}年{{ periods|slice:"5:"}}期
                        {% else %}
                            全部
                        {% endif %}

                    </strong>
                </li>
            </ol>
        </div>
        <div class="col-lg-2">
        </div>
    </div>
{% endblock %}

{% block content %}
    <div class="wrapper wrapper-content animated fadeIn">
        <div class="ibox-content">
            <input type="text" class="form-control form-control-sm m-b-xs" id="filter"
                                   placeholder="搜索关键字">
            <table class="footable table table-stripped toggle-arrow-tiny" data-page-size="10" data-filter=#filter>
                <thead>
                <tr>
                    <th data-type="numeric" data-toggle="true">序号</th>
                    <th>缺陷期数</th>
                    <th>产品类型</th>
                    <th>设备型号/软件版本</th>
                    <th data-hide="all">生产厂商</th>
                    <th data-hide="all">缺陷原因</th>
                    <th>缺陷影响</th>
                    <th data-hide="all">解决方案</th>
                    <th data-hide="all">补丁版本</th>
                    <th data-hide="all">解决状态</th>
                    <th data-hide="all">发现时间</th>
                    <th>行内解决方案</th>
                    <th>行内解决状态</th>
                    <th>处理进度</th>
                </tr>
                </thead>
                <tbody>
                {% for defect in all_defects %}
                    <tr>
                        <td>{{ forloop.counter }}</td>
                        <td>{{ defect.periods }}</td>
                        <td>{{ defect.category }}</td>
                        <td>
                            <a href="{% url 'InfoMG:add_defect_detail' defect.id %}" title="添加待处理明细">
                                {{ defect.model }}
                            </a>
                        </td>
                        <td>{{ defect.manufacturer }}</td>
                        <td>{{ defect.reason }}</td>
                        <td>{{ defect.defect }}</td>
                        <td>{{ defect.solution }}</td>
                        <td>{{ defect.fix_pack }}</td>
                        <td>{{ defect.status }}</td>
                        <td>{{ defect.find_date }}</td>
                        <td>
                            <a title="添加解决方案"
                               data-toggle="modal"
                               href="#v_solution-form"
                               data-whatever="{{ defect.id }}">
                                {% if defect.v_solution %}
                                    {{ defect.v_solution }}
                                {% else %}
                                    待录入
                                {% endif %}
                            </a>
                        </td>
                        <td>
                            {% if defect.v_flag == '0' %}
                                待解决
                            {% elif defect.v_flag == '1' %}
                                已解决
                            {% elif defect.v_flag == '2' %}
                                无需处理
                            {% else %}
                                {{ defect.v_flag }}
                            {% endif %}
                        </td>
                        <td>
                            {% if defect.all_details_count == 0 %}
                                无待处理明细
                            {% else %}
                                {{ defect.solved_details_count }}/{{ defect.all_details_count }}
                            {% endif %}
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
                <tfoot>
                <tr>
                    <td colspan="5">
                        <ul class="pagination float-right"></ul>
                    </td>
                </tr>
                </tfoot>
            </table>
        </div>
    </div>

    <!-- 缺陷行内解决方案弹出框 -->
    <div id="v_solution-form" class="modal fade" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-body">
                    <div class="row">
                        <div class="col-sm-12">
                            <h3 class="m-t-none m-b">添加行内解决方案</h3>
                            <p></p>
                            <form role="form" method="post" action="">
                                {% csrf_token %}
                                <div class="form-group row">
                                    <textarea class="form-control message-input"
                                              placeholder="最多可以输入200个字符"
                                              maxlength="200"
                                              name="v_solution"></textarea>
                                </div>
                                <div class="model_defect_id" style="display: none"></div>
                                <div>
                                    <button class="btn btn-lg btn-primary m-t-n-xs"
                                            type="button" name="confirm"
                                            style="margin-left: 280px">
                                        <strong>无需处理</strong>
                                    </button>
                                    <button class="btn btn-lg btn-info float-right m-t-n-xs"
                                            type="button" name="add_v_solution">
                                        <strong>确认</strong>
                                    </button>
                                </div>
                                <p style="color: red" id="add_v_solution_msg"></p>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block custom_js %}
    <script src="{% static 'js/plugins/metisMenu/jquery.metisMenu.js' %}"></script>
    <script src="{% static 'js/plugins/slimscroll/jquery.slimscroll.min.js' %}"></script>
    <script src="{% static 'js/plugins/footable/footable.all.min.js' %}"></script>

    <script src="{% static 'js/inspinia.js' %}"></script>
    <script src="{% static 'js/plugins/pace/pace.min.js' %}"></script>
{% endblock %}

{% block custom_page_js %}
    <script>
        $(document).ready(function() {
            $('.footable').footable();
        });

        let source = ''
        $('#v_solution-form').on('show.bs.modal', function (event) {
            source = $(event.relatedTarget);
            const defect_id = source.data('whatever')
            $(".model_defect_id").text(defect_id)
        })

        $("button[name='add_v_solution']").bind("click", function () {
            const tds = source.parent().parent().find('td')
            const v_solution = $("textarea[name='v_solution']").val()
            const defect_id = $(".model_defect_id").text()
            if (v_solution === '') alert("请输入解决方案")
            else {
                $.ajax({
                    url: '{% url 'InfoMG:add_v_solution' %}',
                    type: 'post',
                    data: {
                        defect_id: defect_id,
                        v_solution: v_solution,
                        csrfmiddlewaretoken: '{{ csrf_token }}',
                    },
                    success: function (data) {
                        if (data === 'success') {
                            $("#v_solution-form").modal("hide");
                            window.location.reload()
                        }
                        else alert('添加失败，请联系系统管理员！')
                    }
                })
            }
        })

        $("button[name='confirm']").bind("click", function () {
            const tds = source.parent().parent().find('td')
            const v_solution = $("textarea[name='v_solution']").val()
            const defect_id = $(".model_defect_id").text()
            if (v_solution === '') alert("请输入解决方案")
            else {
                $.ajax({
                    url: '{% url 'InfoMG:update_defect_v_flag' %}',
                    type: 'post',
                    data: {
                        defect_id: defect_id,
                        v_solution: v_solution,
                        csrfmiddlewaretoken: '{{ csrf_token }}',
                    },
                    success: function (data) {
                        if (data === 'success') {
                            $("#v_solution-form").modal("hide");
                            window.location.reload()
                        }
                        else alert('添加失败，请联系系统管理员！')
                    }
                })
            }
        })
    </script>
{% endblock %}